//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIX.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessToken
    {
        public System.Guid TokenId { get; set; }
        public string TokenKey { get; set; }
        public int UserId { get; set; }
        public string Purpose { get; set; }
        public int StatusId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ExpiredTimestamp { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
