//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIX.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyTrading
    {
        public int TradeId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> EURJPY { get; set; }
        public Nullable<decimal> EURUSD { get; set; }
        public Nullable<decimal> EURNZD { get; set; }
        public Nullable<decimal> USDCAD { get; set; }
        public Nullable<decimal> GBPUSD { get; set; }
        public Nullable<decimal> USDSGD { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public Nullable<System.DateTime> ModifiedTimestamp { get; set; }
    }
}
