//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIX.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocSequence
    {
        public int DocId { get; set; }
        public string Description { get; set; }
        public string Prefix { get; set; }
        public int Length { get; set; }
        public int Current { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
