//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIX.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchingBonus
    {
        public int MatchingBonusId { get; set; }
        public int UserPackageId { get; set; }
        public int UserId { get; set; }
        public int ReferralId { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int Generation { get; set; }
        public decimal Rate { get; set; }
        public decimal BonusAmount { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> ModifiedTimestamp { get; set; }
        public string ApprovedReferenceNo { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual UserPackage UserPackage { get; set; }
        public virtual Status Status { get; set; }
    }
}
