//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIX.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBankAccount
    {
        public System.Guid UBAId { get; set; }
        public int UserId { get; set; }
        public int BankId { get; set; }
        public string BankAccountNo { get; set; }
        public string BankAccountHolder { get; set; }
        public string BankBranch { get; set; }
        public bool IsPrimary { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public Nullable<System.DateTime> ModifiedTimestamp { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual User User { get; set; }
    }
}
