//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIX.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPendingReturnInvestor
    {
        public int UPDId { get; set; }
        public string Username { get; set; }
        public System.DateTime Date { get; set; }
        public string Package { get; set; }
        public decimal TotalInvest { get; set; }
        public decimal InterestRate { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
    }
}
