// <auto-generated />
namespace FIX.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedcascadeOnDeleteonuserprofileconfig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedcascadeOnDeleteonuserprofileconfig));
        
        string IMigrationMetadata.Id
        {
            get { return "201706111621263_Added cascadeOnDelete on userprofileconfig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
